services:
  cartdb:
    container_name: cartdb    
    restart: always
    ports:
      - "27018:27017"   
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network      
  
  mssqldb:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin!1234"
    ports:
      - "1433:1433"
    volumes:
      - db_mssql_data:/var/opt/mssql
    networks:
      - my_network
            
  cart.api:
    container_name: cart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://cartdb:27017"
    ports:
      - "8000:8080"
      - "8001:8081"
    depends_on:
      - cartdb
    networks:
      - my_network 

  catalog.api:   
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=Server=mssqldb;Database=CatalogDb;User Id=sa;Password=Admin!1234;TrustServerCertificate=True
    ports:
      - "8002:8080" 
      - "8003:8081"
    depends_on:
      - mssqldb
    networks:
      - my_network
  
  healthchecks-ui:
    container_name: healthchecks-ui
    build:
      context: .
      dockerfile: src/WebStatus/HealthCheck.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8005:8080"
    depends_on:
      - cart.api
      - catalog.api      
    networks:
      - my_network
    volumes:
      - healthchecks-ui-storage:/storage

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  prometheus:
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - my_network
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - my_network      

volumes:
  mongo_data:
  grafana_data:
  healthchecks-ui-storage:
  db_mssql_data:
  portainer_data:

networks:
  my_network:
    driver: bridge
