@Catalog.API_HostAddress = http://localhost:5092

### Get Categories
GET {{Catalog.API_HostAddress}}/api/categories
Accept: application/json

### Get Products
GET {{Catalog.API_HostAddress}}/api/products
Accept: application/json

###
